<h1 style="text-align: center;"><a title="Data Prep-AIMS-Cmr-2024-25">Assignment 1, Data Prep  @AIMSSen 25</h1>

**Instructor:** 

* Rockefeller

# Exercice 1:  Trends in Business in Nigeria

**NaijaBiz Analytics** is a leading business intelligence firm that specializes in analyzing small and medium enterprises (SMEs) across Nigeria. The company has been contracted by the Nigerian Ministry of Industry, Trade and Investment to conduct a comprehensive analysis of business performance across different states and sectors. 

As a newly hired Data Analyst at NaijaBiz Analytics, you have been provided with a dataset containing information about businesses across various Nigerian states. Your task is to analyze the business data using basic filtering operations to provide actionable insights.

**Dataset:** `naija_businesses.csv`

For each question below, provide the Python pandas code and extract meaningful business insights from your analysis.

In [6]:
import pandas as pd

In [7]:
# This is a dataset containing information about businesses across varoius Nigerian States
df_naija_businesses = pd.read_csv('/home/students-aimssn/Documents/Data_Prep/A1_data_prep/data/naija_businesses.csv')

In [8]:
df_naija_businesses

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
0,NG_0001,Business_1,Benue,Retail,2023-02-01,417741,406718,8,False,True
1,NG_0002,Business_2,Kaduna,Manufacturing,2023-11-17,696804,256593,10,True,False
2,NG_0003,Business_3,Oyo,Technology,2020-09-02,520713,87719,11,False,True
3,NG_0004,Business_4,Benue,Manufacturing,2023-04-14,553527,389310,7,False,True
4,NG_0005,Business_5,Rivers,Technology,2022-11-28,231537,-11869,10,True,False
...,...,...,...,...,...,...,...,...,...,...
195,NG_0196,Business_196,Kano,Services,2023-09-27,611128,415487,8,True,False
196,NG_0197,Business_197,Kano,Agriculture,2021-01-31,916895,349547,7,False,True
197,NG_0198,Business_198,Kaduna,Agriculture,2021-11-29,778180,430501,8,False,True
198,NG_0199,Business_199,Oyo,Agriculture,2022-11-08,98486,78788,4,False,True
199,NG_0200,Business_200,Rivers,Retail,2020-06-25,713491,339290,10,False,False

### Q1: High Revenue Businesses
Filter and display all businesses that have monthly revenue greater than 600,000 Naira. How many such businesses exist?

**Business Context:** Identifying high-revenue businesses can help understand successful business models.

In [9]:
# This display businesses that have monthly revenue greater than 600,000 Naira
high_revenue_businesses = df_naija_businesses[df_naija_businesses['monthly_revenue_naira'] > 600000]

In [10]:
high_revenue_businesses

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
1,NG_0002,Business_2,Kaduna,Manufacturing,2023-11-17,696804,256593,10,True,False
6,NG_0007,Business_7,Oyo,Services,2021-06-21,724708,207436,12,False,True
7,NG_0008,Business_8,Oyo,Technology,2022-07-09,928641,111173,11,False,False
11,NG_0012,Business_12,Benue,Services,2022-06-21,835058,436180,7,False,True
12,NG_0013,Business_13,Rivers,Manufacturing,2020-02-05,677796,298681,6,False,True
18,NG_0019,Business_19,Anambra,Manufacturing,2021-10-15,677240,486295,8,False,True
27,NG_0028,Business_28,Kano,Retail,2020-02-20,713895,168645,10,False,False
29,NG_0030,Business_30,Kaduna,Retail,2023-04-28,872155,371524,6,False,True
30,NG_0031,Business_31,Oyo,Services,2023-02-22,795650,40562,3,False,True
36,NG_0037,Business_37,Kaduna,Services,2021-11-12,788749,212612,10,False,True
38,NG_0039,Business_39,Lagos,Technology,2022-12-13,670388,289248,4,False,True
39,NG_0040,Business_40,Rivers,Retail,2022-09-29,653667,146427,6,False,False
40,NG_0041,Business_41,Rivers,Services,2021-03-19,610938,493260,8,True,True
41,NG_0042,Business_42,Benue,Agriculture,2021-09-04,646634,369677,14,False,True
43,NG_0044,Business_44,Anambra,Services,2020-09-20,652314,525753,8,False,True
48,NG_0049,Business_49,Imo,Agriculture,2023-05-04,771763,379787,7,False,False
54,NG_0055,Business_55,Benue,Technology,2020-02-16,668714,411354,9,False,False
58,NG_0059,Business_59,Rivers,Retail,2021-10-17,787350,224882,7,True,True
72,NG_0073,Business_73,Lagos,Services,2023-11-17,845549,19897,11,False,False
76,NG_0077,Business_77,Kaduna,Agriculture,2021-05-27,836936,555873,6,False,False
79,NG_0080,Business_80,Kaduna,Retail,2023-02-15,707431,451484,10,False,False
83,NG_0084,Business_84,Anambra,Services,2022-06-15,805420,163626,4,False,True
85,NG_0086,Business_86,Rivers,Manufacturing,2023-04-27,787236,294178,9,False,True
87,NG_0088,Business_88,Lagos,Manufacturing,2021-08-03,746502,157898,14,False,False
90,NG_0091,Business_91,Anambra,Services,2020-09-03,827771,308273,5,False,False
93,NG_0094,Business_94,Imo,Manufacturing,2023-12-29,661511,529208,10,False,True
94,NG_0095,Business_95,Imo,Retail,2022-09-23,684830,512137,8,False,True
95,NG_0096,Business_96,Imo,Retail,2023-01-14,662571,228961,6,False,True
106,NG_0107,Business_107,Imo,Agriculture,2023-05-12,755092,422053,7,False,True
108,NG_0109,Business_109,Imo,Manufacturing,2020-08-05,687414,259674,7,True,True
111,NG_0112,Business_112,Benue,Agriculture,2020-12-06,768417,534705,14,False,False
114,NG_0115,Business_115,Benue,Technology,2023-07-01,618748,205519,3,False,True
115,NG_0116,Business_116,Kaduna,Technology,2020-12-22,742563,272479,8,True,True
118,NG_0119,Business_119,Anambra,Retail,2023-01-28,822115,239632,8,False,True
119,NG_0120,Business_120,Oyo,Services,2022-03-12,754798,235629,15,False,True
123,NG_0124,Business_124,Benue,Retail,2021-03-17,843719,190578,3,False,True
124,NG_0125,Business_125,Oyo,Manufacturing,2022-02-07,673214,62488,9,False,False
128,NG_0129,Business_129,Kaduna,Manufacturing,2022-11-05,693725,371297,9,False,False
129,NG_0130,Business_130,Kaduna,Services,2022-03-02,629146,497825,7,True,False
130,NG_0131,Business_131,Kaduna,Retail,2020-12-01,742431,268497,11,True,False
137,NG_0138,Business_138,Lagos,Services,2021-01-14,682921,70535,10,False,False
139,NG_0140,Business_140,Lagos,Retail,2021-11-21,906428,195267,11,False,False
141,NG_0142,Business_142,Lagos,Retail,2023-07-15,799977,191905,10,False,True
143,NG_0144,Business_144,Anambra,Retail,2023-04-06,612206,77294,6,False,True
145,NG_0146,Business_146,Benue,Manufacturing,2020-10-11,834749,364417,5,False,True
147,NG_0148,Business_148,Rivers,Retail,2020-01-12,714736,326393,5,False,True
150,NG_0151,Business_151,Rivers,Services,2021-05-13,623221,140961,7,False,False
157,NG_0158,Business_158,Kano,Technology,2021-08-27,602588,213962,7,False,True
163,NG_0164,Business_164,Kaduna,Technology,2023-05-04,894692,572702,10,False,True
173,NG_0174,Business_174,Kaduna,Services,2021-11-06,819422,255845,9,False,False
176,NG_0177,Business_177,Rivers,Technology,2022-07-08,673369,261477,10,True,False
179,NG_0180,Business_180,Rivers,Technology,2023-01-27,680372,351148,10,False,True
183,NG_0184,Business_184,Rivers,Manufacturing,2021-10-24,615234,451551,12,False,False
184,NG_0185,Business_185,Lagos,Technology,2023-04-28,737919,444418,2,False,True
193,NG_0194,Business_194,Benue,Agriculture,2021-08-18,934568,261431,9,True,True
194,NG_0195,Business_195,Benue,Agriculture,2021-12-29,812562,504472,11,False,True
195,NG_0196,Business_196,Kano,Services,2023-09-27,611128,415487,8,True,False
196,NG_0197,Business_197,Kano,Agriculture,2021-01-31,916895,349547,7,False,True
197,NG_0198,Business_198,Kaduna,Agriculture,2021-11-29,778180,430501,8,False,True
199,NG_0200,Business_200,Rivers,Retail,2020-06-25,713491,339290,10,False,False

In [11]:
# This is to determine the high business model that understand successful business model
high_revenue_count = len(high_revenue_businesses)

In [12]:
# This shows the total number of high revenue businesses in percentage(100%)
high_revenue_count

60

### The Business insight: 

**The retail will emerges as a  dominant low-cost business model, because it demonstrates the sector to offer a vital opportunities for economic that has low capital demand**.

### Q2: Technology Businesses with Websites
Filter businesses that are in the "Technology" sector AND have a website. Display their business names and monthly revenue.

**Business Context:** Understanding digital adoption in the tech sector can inform technology support programs.

In [15]:
# This is a dataset of business that in the technology
business_in_tech = df_naija_businesses[
    (df_naija_businesses['business_type'] == 'Technology') & (df_naija_businesses['has_website'] == True)
]

In [ ]:
# This is a dataset of business that into technology as displayed below
business_in_tech

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
4,NG_0005,Business_5,Rivers,Technology,2022-11-28,231537,-11869,10,True,False
9,NG_0010,Business_10,Kano,Technology,2021-06-08,549862,293803,3,True,False
33,NG_0034,Business_34,Kano,Technology,2021-07-23,265604,8259,8,True,True
74,NG_0075,Business_75,Oyo,Technology,2022-12-17,370740,296592,6,True,True
115,NG_0116,Business_116,Kaduna,Technology,2020-12-22,742563,272479,8,True,True
144,NG_0145,Business_145,Anambra,Technology,2022-12-02,349510,294444,8,True,True
161,NG_0162,Business_162,Lagos,Technology,2020-04-24,319976,255980,12,True,False
176,NG_0177,Business_177,Rivers,Technology,2022-07-08,673369,261477,10,True,False

In [17]:
business_tech_count= len(business_in_tech)

In [18]:
# when filtered I discover only eight buinesses only 
business_tech_count

8

### The Business insight: 

**The retail will emerges as a  dominant low-cost business model, because it demonstrates the sector to offer a vital opportunities for economic that has low capital demand**.

### Q3: Manufacturing Businesses in Specific States
Filter all Manufacturing businesses located in either "Lagos" OR "Kano" states. How many manufacturing businesses are in these two states?

**Business Context:** These states are major industrial hubs, and this analysis helps understand manufacturing concentration.

In [19]:
specific_state_manufacturing = df_naija_businesses[
    (df_naija_businesses['business_type'] == 'Manufacturing') & 
    (df_naija_businesses['state'].isin(['Lagos', 'Kano']))
]

In [20]:
specific_state_manufacturing

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
22,NG_0023,Business_23,Kano,Manufacturing,2023-01-20,589101,332379,11,False,False
42,NG_0043,Business_43,Kano,Manufacturing,2022-09-19,279155,216038,4,False,True
70,NG_0071,Business_71,Kano,Manufacturing,2022-03-01,435325,336302,8,False,True
75,NG_0076,Business_76,Kano,Manufacturing,2021-09-25,419289,335431,6,False,False
87,NG_0088,Business_88,Lagos,Manufacturing,2021-08-03,746502,157898,14,False,False
92,NG_0093,Business_93,Kano,Manufacturing,2020-06-02,533285,147207,8,False,True
105,NG_0106,Business_106,Kano,Manufacturing,2021-03-28,414793,82169,6,False,True
122,NG_0123,Business_123,Kano,Manufacturing,2022-01-31,572033,141804,5,False,True
127,NG_0128,Business_128,Lagos,Manufacturing,2021-05-30,123223,98578,6,False,True
165,NG_0166,Business_166,Lagos,Manufacturing,2023-01-03,288084,230467,11,True,False

In [21]:
manufactruing_states_count= len(specific_state_manufacturing)

In [22]:
manufactruing_states_count

10

### Q4: Small Businesses Analysis
Filter businesses that have fewer than 5 employees AND monthly costs less than 200,000 Naira. What business types do these small businesses represent?

**Business Context:** Small businesses often need different support strategies than larger enterprises.

In [23]:
small_business = df_naija_businesses[
    (df_naija_businesses['employees'] < 5) & (df_naija_businesses['monthly_costs_naira'] < 200000)
   ]

In [ ]:
small_business

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
16,NG_0017,Business_17,Kaduna,Retail,2021-05-26,212107,169685,2,True,False
23,NG_0024,Business_24,Anambra,Services,2023-10-09,207648,166118,4,False,True
30,NG_0031,Business_31,Oyo,Services,2023-02-22,795650,40562,3,False,True
57,NG_0058,Business_58,Lagos,Services,2022-07-24,306577,43908,4,True,True
71,NG_0072,Business_72,Kano,Services,2023-02-24,167976,70428,1,False,True
83,NG_0084,Business_84,Anambra,Services,2022-06-15,805420,163626,4,False,True
89,NG_0090,Business_90,Kano,Agriculture,2022-05-10,403124,-29477,4,False,True
123,NG_0124,Business_124,Benue,Retail,2021-03-17,843719,190578,3,False,True
138,NG_0139,Business_139,Benue,Technology,2022-08-14,65023,52018,4,False,False
153,NG_0154,Business_154,Rivers,Services,2021-12-27,239679,13311,4,False,True
156,NG_0157,Business_157,Benue,Agriculture,2022-02-14,70828,56662,4,True,False
181,NG_0182,Business_182,Benue,Manufacturing,2022-10-05,454650,88372,3,False,True
198,NG_0199,Business_199,Oyo,Agriculture,2022-11-08,98486,78788,4,False,True

In [ ]:
small_business_count = len(small_business)

In [ ]:
small_business_count

13

In [ ]:
percent_result = (len(small_business)/len(df_naija_data)) * 100

In [ ]:
print("The prercentage of small business is: ",round(percent_result, 2), "%" )

The prercentage of small business is:  6.5 %

### The Business insight here: 

**From the above table, I undsertand it is a small scale business or micro type of business that meet up the demand or requirement.**
**They are about tweenty-three percent (6.5%).**

### Q5: Profitable Retail Businesses
Filter Retail businesses where monthly revenue is greater than monthly costs. Display their state and employee count.

**Business Context:** Understanding profitable retail operations can help identify successful business practices.

In [ ]:
profitable_retail = df_naija_businesses[
    (df_naija_businesses['business_type']== 'Retail') & (df_naija_businesses['monthly_revenue_naira'] > df_naija_businesses['monthly_costs_naira'])
    ]

In [ ]:
profitable_retail

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
0,NG_0001,Business_1,Benue,Retail,2023-02-01,417741,406718,8,False,True
16,NG_0017,Business_17,Kaduna,Retail,2021-05-26,212107,169685,2,True,False
26,NG_0027,Business_27,Imo,Retail,2022-05-03,151342,121073,12,False,True
27,NG_0028,Business_28,Kano,Retail,2020-02-20,713895,168645,10,False,False
28,NG_0029,Business_29,Anambra,Retail,2021-07-28,467226,270305,3,True,True
29,NG_0030,Business_30,Kaduna,Retail,2023-04-28,872155,371524,6,False,True
31,NG_0032,Business_32,Lagos,Retail,2020-05-29,324106,259284,3,False,True
34,NG_0035,Business_35,Imo,Retail,2023-09-27,182707,89967,5,True,True
37,NG_0038,Business_38,Lagos,Retail,2022-04-17,117018,93614,10,True,True
39,NG_0040,Business_40,Rivers,Retail,2022-09-29,653667,146427,6,False,False
44,NG_0045,Business_45,Kaduna,Retail,2022-12-12,390148,223739,8,False,False
46,NG_0047,Business_47,Anambra,Retail,2020-01-05,511482,327526,11,False,True
47,NG_0048,Business_48,Benue,Retail,2023-01-31,331178,264942,2,False,True
53,NG_0054,Business_54,Kaduna,Retail,2023-10-05,479231,197888,5,False,False
55,NG_0056,Business_56,Kaduna,Retail,2022-05-16,286735,229388,8,False,True
56,NG_0057,Business_57,Anambra,Retail,2022-04-02,359637,287709,9,True,True
58,NG_0059,Business_59,Rivers,Retail,2021-10-17,787350,224882,7,True,True
63,NG_0064,Business_64,Lagos,Retail,2021-10-18,352514,282011,8,False,True
64,NG_0065,Business_65,Benue,Retail,2020-04-29,592544,474035,13,True,True
73,NG_0074,Business_74,Kano,Retail,2022-10-09,201479,185281,10,False,True
78,NG_0079,Business_79,Benue,Retail,2023-01-24,528410,424223,7,False,True
79,NG_0080,Business_80,Kaduna,Retail,2023-02-15,707431,451484,10,False,False
94,NG_0095,Business_95,Imo,Retail,2022-09-23,684830,512137,8,False,True
95,NG_0096,Business_96,Imo,Retail,2023-01-14,662571,228961,6,False,True
97,NG_0098,Business_98,Kaduna,Retail,2023-08-01,372552,279734,9,True,True
100,NG_0101,Business_101,Benue,Retail,2022-12-06,325579,260463,5,False,False
101,NG_0102,Business_102,Kano,Retail,2022-10-05,365795,353725,11,False,True
107,NG_0108,Business_108,Kaduna,Retail,2022-06-30,481686,74825,9,False,False
110,NG_0111,Business_111,Anambra,Retail,2021-03-07,582742,396503,9,False,True
117,NG_0118,Business_118,Imo,Retail,2021-06-05,509914,229457,10,False,False
118,NG_0119,Business_119,Anambra,Retail,2023-01-28,822115,239632,8,False,True
123,NG_0124,Business_124,Benue,Retail,2021-03-17,843719,190578,3,False,True
126,NG_0127,Business_127,Kano,Retail,2023-09-10,544014,180524,10,True,False
130,NG_0131,Business_131,Kaduna,Retail,2020-12-01,742431,268497,11,True,False
132,NG_0133,Business_133,Lagos,Retail,2021-05-11,525608,66637,8,True,True
139,NG_0140,Business_140,Lagos,Retail,2021-11-21,906428,195267,11,False,False
141,NG_0142,Business_142,Lagos,Retail,2023-07-15,799977,191905,10,False,True
143,NG_0144,Business_144,Anambra,Retail,2023-04-06,612206,77294,6,False,True
147,NG_0148,Business_148,Rivers,Retail,2020-01-12,714736,326393,5,False,True
148,NG_0149,Business_149,Lagos,Retail,2023-08-18,515209,99055,14,False,False
158,NG_0159,Business_159,Lagos,Retail,2022-08-27,256302,205041,9,True,True
160,NG_0161,Business_161,Benue,Retail,2021-02-21,491674,52389,8,False,False
167,NG_0168,Business_168,Benue,Retail,2023-10-31,344953,297311,10,True,False
168,NG_0169,Business_169,Benue,Retail,2023-12-14,504750,255204,5,False,True
175,NG_0176,Business_176,Imo,Retail,2021-04-01,525486,318756,10,True,True
178,NG_0179,Business_179,Lagos,Retail,2022-01-08,428358,56621,5,True,True
182,NG_0183,Business_183,Imo,Retail,2020-04-05,345782,43724,6,False,True
186,NG_0187,Business_187,Kano,Retail,2023-10-24,515053,412042,10,False,False
189,NG_0190,Business_190,Imo,Retail,2022-05-16,261347,209077,8,False,True
199,NG_0200,Business_200,Rivers,Retail,2020-06-25,713491,339290,10,False,False

In [ ]:
profitable_retail_count = len(profitable_retail)

In [ ]:
profitable_retail_count

50

In [ ]:
df_naija_businesses[['state','employees']]

      state  employees
0     Benue          8
1    Kaduna         10
2       Oyo         11
3     Benue          7
4    Rivers         10
..      ...        ...
195    Kano          8
196    Kano          7
197  Kaduna          8
198     Oyo          4
199  Rivers         10

[200 rows x 2 columns]

### Q6: Businesses Accepting Mobile Money
Filter all businesses that accept mobile money AND have more than 8 employees. Which states are these businesses located in?

**Business Context:** Larger businesses adopting mobile payments indicate financial technology integration.

In [24]:
mobile_money_business = df_naija_businesses[
    (df_naija_businesses['accepts_mobile_money'] == True) & 
    (df_naija_businesses['employees'] > 8)
]

In [ ]:
mobile_money_business

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
2,NG_0003,Business_3,Oyo,Technology,2020-09-02,520713,87719,11,False,True
6,NG_0007,Business_7,Oyo,Services,2021-06-21,724708,207436,12,False,True
10,NG_0011,Business_11,Rivers,Services,2022-04-07,564903,326094,16,False,True
13,NG_0014,Business_14,Rivers,Agriculture,2021-11-15,599212,367711,13,False,True
21,NG_0022,Business_22,Oyo,Manufacturing,2023-03-12,264774,211819,9,True,True
26,NG_0027,Business_27,Imo,Retail,2022-05-03,151342,121073,12,False,True
35,NG_0036,Business_36,Oyo,Services,2020-10-31,415564,334449,10,False,True
36,NG_0037,Business_37,Kaduna,Services,2021-11-12,788749,212612,10,False,True
37,NG_0038,Business_38,Lagos,Retail,2022-04-17,117018,93614,10,True,True
41,NG_0042,Business_42,Benue,Agriculture,2021-09-04,646634,369677,14,False,True
45,NG_0046,Business_46,Kaduna,Manufacturing,2022-09-30,8161,6528,16,True,True
46,NG_0047,Business_47,Anambra,Retail,2020-01-05,511482,327526,11,False,True
56,NG_0057,Business_57,Anambra,Retail,2022-04-02,359637,287709,9,True,True
64,NG_0065,Business_65,Benue,Retail,2020-04-29,592544,474035,13,True,True
66,NG_0067,Business_67,Kaduna,Agriculture,2022-12-17,229509,118424,11,False,True
69,NG_0070,Business_70,Imo,Agriculture,2020-04-26,232431,185944,10,False,True
73,NG_0074,Business_74,Kano,Retail,2022-10-09,201479,185281,10,False,True
77,NG_0078,Business_78,Kaduna,Services,2022-03-12,153936,123148,12,False,True
84,NG_0085,Business_85,Benue,Manufacturing,2023-07-19,376842,301473,10,True,True
85,NG_0086,Business_86,Rivers,Manufacturing,2023-04-27,787236,294178,9,False,True
93,NG_0094,Business_94,Imo,Manufacturing,2023-12-29,661511,529208,10,False,True
97,NG_0098,Business_98,Kaduna,Retail,2023-08-01,372552,279734,9,True,True
98,NG_0099,Business_99,Imo,Services,2023-05-28,368694,294955,10,False,True
101,NG_0102,Business_102,Kano,Retail,2022-10-05,365795,353725,11,False,True
110,NG_0111,Business_111,Anambra,Retail,2021-03-07,582742,396503,9,False,True
119,NG_0120,Business_120,Oyo,Services,2022-03-12,754798,235629,15,False,True
120,NG_0121,Business_121,Anambra,Services,2023-04-18,326283,228986,9,True,True
135,NG_0136,Business_136,Oyo,Agriculture,2022-05-01,379548,303638,9,False,True
136,NG_0137,Business_137,Lagos,Agriculture,2021-11-20,136139,108911,10,False,True
141,NG_0142,Business_142,Lagos,Retail,2023-07-15,799977,191905,10,False,True
155,NG_0156,Business_156,Kano,Services,2020-03-30,402271,321816,9,False,True
158,NG_0159,Business_159,Lagos,Retail,2022-08-27,256302,205041,9,True,True
163,NG_0164,Business_164,Kaduna,Technology,2023-05-04,894692,572702,10,False,True
175,NG_0176,Business_176,Imo,Retail,2021-04-01,525486,318756,10,True,True
177,NG_0178,Business_178,Rivers,Technology,2020-07-10,594207,453642,10,False,True
179,NG_0180,Business_180,Rivers,Technology,2023-01-27,680372,351148,10,False,True
180,NG_0181,Business_181,Oyo,Services,2022-09-04,325750,303835,12,False,True
191,NG_0192,Business_192,Rivers,Agriculture,2023-07-20,421793,141370,11,True,True
193,NG_0194,Business_194,Benue,Agriculture,2021-08-18,934568,261431,9,True,True
194,NG_0195,Business_195,Benue,Agriculture,2021-12-29,812562,504472,11,False,True

### Q7: Low-Cost Operations
Filter businesses where monthly costs are less than 150,000 Naira. What is the most common business type among these low-cost operations?

**Business Context:** Low-cost business models can be important for economic inclusion and job creation.

In [25]:
low_cost_businesses = df_naija_businesses[df_naija_businesses['monthly_costs_naira'] < 150000]

In [ ]:
low_cost_businesses

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
2,NG_0003,Business_3,Oyo,Technology,2020-09-02,520713,87719,11,False,True
4,NG_0005,Business_5,Rivers,Technology,2022-11-28,231537,-11869,10,True,False
5,NG_0006,Business_6,Anambra,Technology,2022-01-28,-172819,-138255,5,False,False
7,NG_0008,Business_8,Oyo,Technology,2022-07-09,928641,111173,11,False,False
26,NG_0027,Business_27,Imo,Retail,2022-05-03,151342,121073,12,False,True
30,NG_0031,Business_31,Oyo,Services,2023-02-22,795650,40562,3,False,True
33,NG_0034,Business_34,Kano,Technology,2021-07-23,265604,8259,8,True,True
34,NG_0035,Business_35,Imo,Retail,2023-09-27,182707,89967,5,True,True
37,NG_0038,Business_38,Lagos,Retail,2022-04-17,117018,93614,10,True,True
39,NG_0040,Business_40,Rivers,Retail,2022-09-29,653667,146427,6,False,False
45,NG_0046,Business_46,Kaduna,Manufacturing,2022-09-30,8161,6528,16,True,True
57,NG_0058,Business_58,Lagos,Services,2022-07-24,306577,43908,4,True,True
65,NG_0066,Business_66,Kano,Services,2022-04-10,291829,63071,6,False,True
66,NG_0067,Business_67,Kaduna,Agriculture,2022-12-17,229509,118424,11,False,True
67,NG_0068,Business_68,Lagos,Technology,2023-10-01,388315,57988,12,False,False
71,NG_0072,Business_72,Kano,Services,2023-02-24,167976,70428,1,False,True
72,NG_0073,Business_73,Lagos,Services,2023-11-17,845549,19897,11,False,False
77,NG_0078,Business_78,Kaduna,Services,2022-03-12,153936,123148,12,False,True
89,NG_0090,Business_90,Kano,Agriculture,2022-05-10,403124,-29477,4,False,True
92,NG_0093,Business_93,Kano,Manufacturing,2020-06-02,533285,147207,8,False,True
105,NG_0106,Business_106,Kano,Manufacturing,2021-03-28,414793,82169,6,False,True
107,NG_0108,Business_108,Kaduna,Retail,2022-06-30,481686,74825,9,False,False
112,NG_0113,Business_113,Anambra,Retail,2021-07-04,-21757,-17405,11,False,False
122,NG_0123,Business_123,Kano,Manufacturing,2022-01-31,572033,141804,5,False,True
124,NG_0125,Business_125,Oyo,Manufacturing,2022-02-07,673214,62488,9,False,False
127,NG_0128,Business_128,Lagos,Manufacturing,2021-05-30,123223,98578,6,False,True
132,NG_0133,Business_133,Lagos,Retail,2021-05-11,525608,66637,8,True,True
133,NG_0134,Business_134,Oyo,Technology,2022-06-14,403732,-117695,7,False,False
136,NG_0137,Business_137,Lagos,Agriculture,2021-11-20,136139,108911,10,False,True
137,NG_0138,Business_138,Lagos,Services,2021-01-14,682921,70535,10,False,False
138,NG_0139,Business_139,Benue,Technology,2022-08-14,65023,52018,4,False,False
140,NG_0141,Business_141,Anambra,Manufacturing,2023-12-21,147174,117739,7,False,False
143,NG_0144,Business_144,Anambra,Retail,2023-04-06,612206,77294,6,False,True
148,NG_0149,Business_149,Lagos,Retail,2023-08-18,515209,99055,14,False,False
150,NG_0151,Business_151,Rivers,Services,2021-05-13,623221,140961,7,False,False
151,NG_0152,Business_152,Rivers,Services,2022-01-23,394255,132308,13,False,False
152,NG_0153,Business_153,Lagos,Technology,2020-02-04,243941,95594,6,False,True
153,NG_0154,Business_154,Rivers,Services,2021-12-27,239679,13311,4,False,True
156,NG_0157,Business_157,Benue,Agriculture,2022-02-14,70828,56662,4,True,False
160,NG_0161,Business_161,Benue,Retail,2021-02-21,491674,52389,8,False,False
164,NG_0165,Business_165,Kano,Services,2022-04-05,424188,69798,9,False,False
178,NG_0179,Business_179,Lagos,Retail,2022-01-08,428358,56621,5,True,True
181,NG_0182,Business_182,Benue,Manufacturing,2022-10-05,454650,88372,3,False,True
182,NG_0183,Business_183,Imo,Retail,2020-04-05,345782,43724,6,False,True
190,NG_0191,Business_191,Benue,Agriculture,2022-05-22,64663,51730,6,False,True
191,NG_0192,Business_192,Rivers,Agriculture,2023-07-20,421793,141370,11,True,True
198,NG_0199,Business_199,Oyo,Agriculture,2022-11-08,98486,78788,4,False,True

In [ ]:
total_low_cost = len(low_cost_businesses)

In [ ]:
total_low_cost

47

In [ ]:

print(f" The number of businesses with monthly costs that is less than ₦150,000 is : {total_low_cost}")

 The number of businesses with monthly costs that is less than ₦150,000 is : 47

In [ ]:
print(f"Percentage of all businesses: {(total_low_cost/len(df_naija_businesses))*100:.1f}%")

Percentage of all businesses: 23.5%

### The Business insight here: 

**The retail will emerges as a  dominant low-cost business model, because it demonstrates the sector to offer a vital opportunities for economic that has low capital demand**.

### Q8: Recent Business Registrations
Filter businesses that started in 2023. Which business type is most common among these new businesses?

**Business Context:** Recent registration trends can indicate emerging business opportunities and economic growth sectors.

In [ ]:
df_naija_businesses ['start_date'] = pd.to_datetime(df_naija_businesses['start_date'])

businesses_start_2023 = df_naija_businesses[
    df_naija_businesses['start_date'].dt.year == 2023]

In [ ]:
businesses_start_2023

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
0,NG_0001,Business_1,Benue,Retail,2023-02-01,417741,406718,8,False,True
1,NG_0002,Business_2,Kaduna,Manufacturing,2023-11-17,696804,256593,10,True,False
3,NG_0004,Business_4,Benue,Manufacturing,2023-04-14,553527,389310,7,False,True
21,NG_0022,Business_22,Oyo,Manufacturing,2023-03-12,264774,211819,9,True,True
22,NG_0023,Business_23,Kano,Manufacturing,2023-01-20,589101,332379,11,False,False
23,NG_0024,Business_24,Anambra,Services,2023-10-09,207648,166118,4,False,True
29,NG_0030,Business_30,Kaduna,Retail,2023-04-28,872155,371524,6,False,True
30,NG_0031,Business_31,Oyo,Services,2023-02-22,795650,40562,3,False,True
34,NG_0035,Business_35,Imo,Retail,2023-09-27,182707,89967,5,True,True
47,NG_0048,Business_48,Benue,Retail,2023-01-31,331178,264942,2,False,True
48,NG_0049,Business_49,Imo,Agriculture,2023-05-04,771763,379787,7,False,False
53,NG_0054,Business_54,Kaduna,Retail,2023-10-05,479231,197888,5,False,False
62,NG_0063,Business_63,Oyo,Technology,2023-02-03,438364,406188,13,False,False
67,NG_0068,Business_68,Lagos,Technology,2023-10-01,388315,57988,12,False,False
71,NG_0072,Business_72,Kano,Services,2023-02-24,167976,70428,1,False,True
72,NG_0073,Business_73,Lagos,Services,2023-11-17,845549,19897,11,False,False
78,NG_0079,Business_79,Benue,Retail,2023-01-24,528410,424223,7,False,True
79,NG_0080,Business_80,Kaduna,Retail,2023-02-15,707431,451484,10,False,False
82,NG_0083,Business_83,Oyo,Technology,2023-06-14,478403,398805,10,False,False
84,NG_0085,Business_85,Benue,Manufacturing,2023-07-19,376842,301473,10,True,True
85,NG_0086,Business_86,Rivers,Manufacturing,2023-04-27,787236,294178,9,False,True
91,NG_0092,Business_92,Kaduna,Services,2023-01-04,545047,436037,7,True,True
93,NG_0094,Business_94,Imo,Manufacturing,2023-12-29,661511,529208,10,False,True
95,NG_0096,Business_96,Imo,Retail,2023-01-14,662571,228961,6,False,True
97,NG_0098,Business_98,Kaduna,Retail,2023-08-01,372552,279734,9,True,True
98,NG_0099,Business_99,Imo,Services,2023-05-28,368694,294955,10,False,True
106,NG_0107,Business_107,Imo,Agriculture,2023-05-12,755092,422053,7,False,True
113,NG_0114,Business_114,Imo,Manufacturing,2023-08-05,368982,295185,2,False,False
114,NG_0115,Business_115,Benue,Technology,2023-07-01,618748,205519,3,False,True
118,NG_0119,Business_119,Anambra,Retail,2023-01-28,822115,239632,8,False,True
120,NG_0121,Business_121,Anambra,Services,2023-04-18,326283,228986,9,True,True
121,NG_0122,Business_122,Oyo,Services,2023-05-31,523282,442782,4,False,True
126,NG_0127,Business_127,Kano,Retail,2023-09-10,544014,180524,10,True,False
140,NG_0141,Business_141,Anambra,Manufacturing,2023-12-21,147174,117739,7,False,False
141,NG_0142,Business_142,Lagos,Retail,2023-07-15,799977,191905,10,False,True
142,NG_0143,Business_143,Kaduna,Manufacturing,2023-12-11,318389,311761,3,False,True
143,NG_0144,Business_144,Anambra,Retail,2023-04-06,612206,77294,6,False,True
148,NG_0149,Business_149,Lagos,Retail,2023-08-18,515209,99055,14,False,False
149,NG_0150,Business_150,Anambra,Manufacturing,2023-06-30,570591,322333,3,False,True
163,NG_0164,Business_164,Kaduna,Technology,2023-05-04,894692,572702,10,False,True
165,NG_0166,Business_166,Lagos,Manufacturing,2023-01-03,288084,230467,11,True,False
167,NG_0168,Business_168,Benue,Retail,2023-10-31,344953,297311,10,True,False
168,NG_0169,Business_169,Benue,Retail,2023-12-14,504750,255204,5,False,True
170,NG_0171,Business_171,Anambra,Manufacturing,2023-07-24,492960,316459,9,False,False
174,NG_0175,Business_175,Anambra,Manufacturing,2023-11-18,449416,359532,7,True,True
179,NG_0180,Business_180,Rivers,Technology,2023-01-27,680372,351148,10,False,True
184,NG_0185,Business_185,Lagos,Technology,2023-04-28,737919,444418,2,False,True
186,NG_0187,Business_187,Kano,Retail,2023-10-24,515053,412042,10,False,False
191,NG_0192,Business_192,Rivers,Agriculture,2023-07-20,421793,141370,11,True,True
195,NG_0196,Business_196,Kano,Services,2023-09-27,611128,415487,8,True,False

In [ ]:
businesses_start_2023_count = len(businesses_start_2023)

In [ ]:
print(f"Percentage of all businesses: {(businesses_start_2023_count/len(df_naija_businesses))*100:.1f}%")

Percentage of all businesses: 25.0%

## Driven Business Context are:
**The retail will continue to dominate new business registrations in 2023.**
 **The fame of  entrepreneurial activity wil increase.**
  **The balanced mixture of business types can suggests different  economic growth rather than just the  considering a single sector.**

**There are some top pefoming business in 2023 such as retail in kanduna for busines_30 and few others**

### Q9: Large Employers
Filter businesses that have 10 or more employees. Calculate the average monthly revenue of these larger employers.

**Business Context:** Large employers are important for job creation and economic stability.

In [ ]:
large_employers = df_naija_businesses [df_naija_businesses['employees'] >= 10]

In [ ]:
large_employers

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
1,NG_0002,Business_2,Kaduna,Manufacturing,2023-11-17,696804,256593,10,True,False
2,NG_0003,Business_3,Oyo,Technology,2020-09-02,520713,87719,11,False,True
4,NG_0005,Business_5,Rivers,Technology,2022-11-28,231537,-11869,10,True,False
6,NG_0007,Business_7,Oyo,Services,2021-06-21,724708,207436,12,False,True
7,NG_0008,Business_8,Oyo,Technology,2022-07-09,928641,111173,11,False,False
...,...,...,...,...,...,...,...,...,...,...
186,NG_0187,Business_187,Kano,Retail,2023-10-24,515053,412042,10,False,False
191,NG_0192,Business_192,Rivers,Agriculture,2023-07-20,421793,141370,11,True,True
192,NG_0193,Business_193,Lagos,Services,2020-03-02,440378,209484,10,False,False
194,NG_0195,Business_195,Benue,Agriculture,2021-12-29,812562,504472,11,False,True
199,NG_0200,Business_200,Rivers,Retail,2020-06-25,713491,339290,10,False,False

In [ ]:
large_employers_count   = len(large_employers)

In [ ]:
print(f" The number of businesses that have 10 or more eployees is : {large_employers_count}")

 The number of businesses that have 10 or more eployees is : 62

In [ ]:
print(f"The percentage of the businesses is : {(large_employers_count/len(df_naija_businesses))*100:.1f}%")

The percentage of the businesses is : 31.0%

### Business context insight:
**There are 31% of businesses that have more than 10 employees**

**Most of the business type here are manufcaturing, services, Technology, Agriclture, and retail** 

**This also indicate that; since there are different sectors, it increases the chance of employment and reduce joblesness in that communties leading to economic stability**

### Q10: Digital-Ready Businesses
Filter businesses that have a website AND accept mobile money. What percentage of the total businesses are digitally ready?

**Business Context:** Digital readiness indicates how prepared businesses are for the modern economy.

In [26]:
e_ready_business = df_naija_businesses [
    (df_naija_businesses['has_website'] == True ) & (df_naija_businesses['accepts_mobile_money'] == True)
]

In [ ]:
e_ready_business

,business_id,business_name,state,business_type,start_date,monthly_revenue_naira,monthly_costs_naira,employees,has_website,accepts_mobile_money
14,NG_0015,Business_15,Anambra,Agriculture,2020-01-20,511114,422377,8,True,True
21,NG_0022,Business_22,Oyo,Manufacturing,2023-03-12,264774,211819,9,True,True
28,NG_0029,Business_29,Anambra,Retail,2021-07-28,467226,270305,3,True,True
33,NG_0034,Business_34,Kano,Technology,2021-07-23,265604,8259,8,True,True
34,NG_0035,Business_35,Imo,Retail,2023-09-27,182707,89967,5,True,True
37,NG_0038,Business_38,Lagos,Retail,2022-04-17,117018,93614,10,True,True
40,NG_0041,Business_41,Rivers,Services,2021-03-19,610938,493260,8,True,True
45,NG_0046,Business_46,Kaduna,Manufacturing,2022-09-30,8161,6528,16,True,True
56,NG_0057,Business_57,Anambra,Retail,2022-04-02,359637,287709,9,True,True
57,NG_0058,Business_58,Lagos,Services,2022-07-24,306577,43908,4,True,True
58,NG_0059,Business_59,Rivers,Retail,2021-10-17,787350,224882,7,True,True
64,NG_0065,Business_65,Benue,Retail,2020-04-29,592544,474035,13,True,True
68,NG_0069,Business_69,Kaduna,Manufacturing,2022-01-10,340352,187933,8,True,True
74,NG_0075,Business_75,Oyo,Technology,2022-12-17,370740,296592,6,True,True
84,NG_0085,Business_85,Benue,Manufacturing,2023-07-19,376842,301473,10,True,True
91,NG_0092,Business_92,Kaduna,Services,2023-01-04,545047,436037,7,True,True
97,NG_0098,Business_98,Kaduna,Retail,2023-08-01,372552,279734,9,True,True
108,NG_0109,Business_109,Imo,Manufacturing,2020-08-05,687414,259674,7,True,True
115,NG_0116,Business_116,Kaduna,Technology,2020-12-22,742563,272479,8,True,True
120,NG_0121,Business_121,Anambra,Services,2023-04-18,326283,228986,9,True,True
132,NG_0133,Business_133,Lagos,Retail,2021-05-11,525608,66637,8,True,True
144,NG_0145,Business_145,Anambra,Technology,2022-12-02,349510,294444,8,True,True
158,NG_0159,Business_159,Lagos,Retail,2022-08-27,256302,205041,9,True,True
174,NG_0175,Business_175,Anambra,Manufacturing,2023-11-18,449416,359532,7,True,True
175,NG_0176,Business_176,Imo,Retail,2021-04-01,525486,318756,10,True,True
178,NG_0179,Business_179,Lagos,Retail,2022-01-08,428358,56621,5,True,True
191,NG_0192,Business_192,Rivers,Agriculture,2023-07-20,421793,141370,11,True,True
193,NG_0194,Business_194,Benue,Agriculture,2021-08-18,934568,261431,9,True,True

In [ ]:
e_ready_business = len(e_ready_business)

print(f"Number of digitally-ready businesses (website + mobile money): {e_ready_business}")

Number of digitally-ready businesses (website + mobile money): 28

In [ ]:
percentage_digitally_ready = (e_ready_business / len(df_naija_businesses)) * 100

In [ ]:
print(f"Percentage of total businesses: {percentage_digitally_ready:.1f}%")

Percentage of total businesses: 14.0%

# Exercise 2: African Agriculture Analysis

**AgriTech Africa** is a research organization analyzing agricultural technology adoption across five African countries. You have been provided with a dataset containing information about farming communities and their technology usage patterns.

For each question below, provide the Python pandas code and provide a key insight you can get from your answer.

In [98]:
import pandas as pd

In [97]:
african_agirculture_info = pd.read_csv('/home/students-aimssn/Documents/Data_Prep/A1_data_prep/data/african_agriculture_dataset.csv')

In [56]:
african_agirculture_info

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
0,Mountain Cultivators Club,South Africa,Barley,39.96,40,Yes,SMS,318.05,Organic,Sprinkler,Yes,1046.21
1,Prairie Cultivators Club,South Africa,Sorghum,77.62,48,No,SMS,704.85,Organic,Drip,No,921.82
2,Prairie Agri Society,Nigeria,Wheat,97.46,14,Yes,SMS,439.41,NaN,Drip,Yes,1072.58
3,Harvest Farmers Union,Nigeria,Maize,27.84,55,No,SMS,668.23,NaN,Sprinkler,No,629.73
4,Valley Farmers Group,Ghana,Sorghum,70.60,53,Yes,Mobile Apps,801.16,NaN,Sprinkler,No,909.69
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Harvest Agri Society,Kenya,Maize,39.93,0,Yes,NaN,246.61,NaN,NaN,Yes,1123.58
1996,Mountain Farmers Group,Nigeria,Maize,50.99,90,No,NaN,205.38,NaN,Drip,Yes,646.68
1997,Prairie Cultivators Club,Ghana,Rice,89.37,43,No,Mobile Apps,603.02,Organic,Drip,No,958.79
1998,Sunrise Agricultural Association,Kenya,Wheat,87.01,99,No,Mobile Apps,370.42,Inorganic,Sprinkler,Yes,677.78
1999,Savannah Farmers Group,Nigeria,Sorghum,57.86,48,No,Mobile Apps,997.68,Inorganic,NaN,Yes,748.18

## Q1: Identifying Technology Leaders
**Business Question:** Which farming communities are leading in technology adoption, and how many of our partner communities have achieved a Technology Adoption Index above 80?

**Context:** Understanding technology leaders helps identify best practices for scaling across other communities.

In [99]:
techonology_lead = african_agirculture_info[african_agirculture_info['Tech_Adoption_Index'] >= 80]

In [101]:
techonology_lead_count  = len(techonology_lead)

In [102]:
techonology_lead_count

409

In [103]:
techonology_lead

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
8,Prairie Agricultural Association,Tanzania,Wheat,23.15,86,Yes,SMS,504.69,Organic,Drip,Yes,621.79
11,Sunrise Growers Coalition,South Africa,Wheat,70.31,85,Yes,SMS,409.37,Organic,Sprinkler,No,1178.04
16,River Agri Society,Tanzania,Sorghum,74.55,83,No,Mobile Apps,691.11,Inorganic,Sprinkler,Yes,719.05
17,Savannah Agri Society,South Africa,Sorghum,14.50,91,No,Mobile Apps,398.23,Inorganic,Drip,Yes,1067.74
20,Savannah Cultivators Club,Kenya,Sorghum,46.27,92,No,SMS,686.81,NaN,NaN,Yes,612.64
...,...,...,...,...,...,...,...,...,...,...,...,...
1991,Meadow Farmers Group,Kenya,Rice,84.23,91,Yes,SMS,273.06,Inorganic,Sprinkler,No,658.16
1993,Golden Agri Society,Kenya,Rice,90.02,80,Yes,Mobile Apps,664.49,NaN,Drip,Yes,710.92
1994,Green Cultivators Club,Nigeria,Wheat,26.81,95,No,SMS,454.72,NaN,Sprinkler,Yes,607.55
1996,Mountain Farmers Group,Nigeria,Maize,50.99,90,No,NaN,205.38,NaN,Drip,Yes,646.68
1998,Sunrise Agricultural Association,Kenya,Wheat,87.01,99,No,Mobile Apps,370.42,Inorganic,Sprinkler,Yes,677.78

In [104]:
techonology_lead['Community_Name']

8       Prairie Agricultural Association
11             Sunrise Growers Coalition
16                    River Agri Society
17                 Savannah Agri Society
20             Savannah Cultivators Club
                      ...
1991                Meadow Farmers Group
1993                 Golden Agri Society
1994              Green Cultivators Club
1996              Mountain Farmers Group
1998    Sunrise Agricultural Association
Name: Community_Name, Length: 409, dtype: object

## Q2: Premium Drone Adoption Analysis
**Business Question:** Among large-scale farming operations (over 70 acres), which communities have invested in drone technology, and where are they located?

**Context:** Large farms with drone adoption represent high-value clients for advanced agricultural technology partnerships.

In [105]:
analyze_large_farm = african_agirculture_info [(african_agirculture_info['Farm_Size'] > 70) &
    african_agirculture_info ['Drone_Usage']==True]

In [106]:
analyze_large_farm

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
1,Prairie Cultivators Club,South Africa,Sorghum,77.62,48,No,SMS,704.85,Organic,Drip,No,921.82
2,Prairie Agri Society,Nigeria,Wheat,97.46,14,Yes,SMS,439.41,NaN,Drip,Yes,1072.58
4,Valley Farmers Group,Ghana,Sorghum,70.60,53,Yes,Mobile Apps,801.16,NaN,Sprinkler,No,909.69
5,Savannah Agri Society,Tanzania,Barley,92.92,30,Yes,SMS,784.90,Organic,Sprinkler,No,872.48
11,Sunrise Growers Coalition,South Africa,Wheat,70.31,85,Yes,SMS,409.37,Organic,Sprinkler,No,1178.04
...,...,...,...,...,...,...,...,...,...,...,...,...
1988,Savannah Cultivators Club,Ghana,Wheat,97.13,29,Yes,Mobile Apps,555.20,Inorganic,Sprinkler,No,663.25
1991,Meadow Farmers Group,Kenya,Rice,84.23,91,Yes,SMS,273.06,Inorganic,Sprinkler,No,658.16
1993,Golden Agri Society,Kenya,Rice,90.02,80,Yes,Mobile Apps,664.49,NaN,Drip,Yes,710.92
1997,Prairie Cultivators Club,Ghana,Rice,89.37,43,No,Mobile Apps,603.02,Organic,Drip,No,958.79
1998,Sunrise Agricultural Association,Kenya,Wheat,87.01,99,No,Mobile Apps,370.42,Inorganic,Sprinkler,Yes,677.78

## Q3: Market Expansion Opportunities
**Business Question:** How many farming communities are operating in our priority markets of South Africa and Kenya?

**Context:** These countries represent key expansion opportunities for agricultural technology solutions.

In [107]:
priority_markets = african_agirculture_info[african_agirculture_info['Country'].isin(['South Africa', 'Kenya'])]

In [108]:
priority_markets

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
0,Mountain Cultivators Club,South Africa,Barley,39.96,40,Yes,SMS,318.05,Organic,Sprinkler,Yes,1046.21
1,Prairie Cultivators Club,South Africa,Sorghum,77.62,48,No,SMS,704.85,Organic,Drip,No,921.82
6,River Growers Coalition,South Africa,Sorghum,68.94,60,No,NaN,437.78,Inorganic,NaN,Yes,897.94
9,Sunrise Growers Coalition,Kenya,Maize,53.98,59,Yes,NaN,883.72,Organic,NaN,No,629.33
11,Sunrise Growers Coalition,South Africa,Wheat,70.31,85,Yes,SMS,409.37,Organic,Sprinkler,No,1178.04
...,...,...,...,...,...,...,...,...,...,...,...,...
1989,Harvest Agri Society,Kenya,Rice,55.40,24,No,SMS,658.68,NaN,Sprinkler,Yes,693.57
1991,Meadow Farmers Group,Kenya,Rice,84.23,91,Yes,SMS,273.06,Inorganic,Sprinkler,No,658.16
1993,Golden Agri Society,Kenya,Rice,90.02,80,Yes,Mobile Apps,664.49,NaN,Drip,Yes,710.92
1995,Harvest Agri Society,Kenya,Maize,39.93,0,Yes,NaN,246.61,NaN,NaN,Yes,1123.58
1998,Sunrise Agricultural Association,Kenya,Wheat,87.01,99,No,Mobile Apps,370.42,Inorganic,Sprinkler,Yes,677.78

In [109]:
total_prority_markets = len(priority_markets)

In [110]:
total_prority_markets

760

## Q4: Underserved Market Identification
**Business Question:** Which countries have small-scale, low-technology farming operations (under 20 acres with Technology Adoption Index below 30) that could benefit from basic technology interventions?

**Context:** Small, low-tech farms represent an underserved market segment requiring tailored entry-level solutions.

In [111]:
low_tech_communities = african_agirculture_info[
    (african_agirculture_info['Farm_Size'] < 20) & (african_agirculture_info['Tech_Adoption_Index'] < 30)
   ]

In [112]:
low_tech_communities

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
15,Meadow Agri Society,Nigeria,Barley,8.72,28,No,SMS,607.82,Organic,Drip,Yes,428.85
41,Valley Agricultural Association,Nigeria,Rice,2.16,28,Yes,SMS,232.53,NaN,Sprinkler,No,522.66
53,River Cultivators Club,South Africa,Barley,9.59,28,Yes,SMS,255.60,Organic,NaN,No,813.43
54,Sunrise Agricultural Association,South Africa,Wheat,3.14,10,No,NaN,531.49,Inorganic,Sprinkler,Yes,405.82
81,Mountain Growers Coalition,Kenya,Rice,13.85,1,No,NaN,801.18,NaN,Sprinkler,No,1007.81
...,...,...,...,...,...,...,...,...,...,...,...,...
1919,Mountain Cultivators Club,Tanzania,Sorghum,15.37,17,No,SMS,786.98,NaN,Sprinkler,Yes,581.72
1957,Prairie Growers Coalition,Nigeria,Barley,16.16,25,No,Mobile Apps,834.51,NaN,Drip,Yes,630.79
1976,Mountain Cultivators Club,Ghana,Wheat,18.76,16,No,Mobile Apps,781.23,Inorganic,Drip,Yes,463.61
1978,Meadow Agri Society,Kenya,Wheat,2.19,2,Yes,NaN,112.96,Inorganic,NaN,Yes,643.36
1990,Golden Farmers Union,Nigeria,Wheat,19.07,6,No,SMS,904.24,NaN,NaN,No,736.37

In [113]:
total_tech_communities = len(low_tech_communities)

In [114]:
total_tech_communities

113

## Q5: Sustainable Agriculture Success Stories
**Business Question:** Which organic farming communities are achieving high productivity (over 600 annual yield), and what irrigation technologies are they using?

**Context:** Successful organic farms demonstrate sustainable practices that can be promoted to environmentally conscious markets.

In [116]:
achieved_organic = african_agirculture_info[
    (african_agirculture_info['Fertilizer_Type'] == 'Organic') & (african_agirculture_info['Annual_Yield'] > 600)
    ]

In [117]:
achieved_organic

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
1,Prairie Cultivators Club,South Africa,Sorghum,77.62,48,No,SMS,704.85,Organic,Drip,No,921.82
5,Savannah Agri Society,Tanzania,Barley,92.92,30,Yes,SMS,784.90,Organic,Sprinkler,No,872.48
7,Savannah Farmers Union,Nigeria,Rice,68.43,57,No,NaN,611.11,Organic,Drip,No,534.91
9,Sunrise Growers Coalition,Kenya,Maize,53.98,59,Yes,NaN,883.72,Organic,NaN,No,629.33
15,Meadow Agri Society,Nigeria,Barley,8.72,28,No,SMS,607.82,Organic,Drip,Yes,428.85
...,...,...,...,...,...,...,...,...,...,...,...,...
1959,Meadow Agricultural Association,Tanzania,Sorghum,65.94,78,No,SMS,756.00,Organic,Sprinkler,Yes,574.38
1963,Valley Growers Coalition,South Africa,Sorghum,36.55,15,Yes,NaN,735.03,Organic,Drip,No,1087.69
1964,Green Farmers Union,Kenya,Barley,13.11,78,Yes,NaN,974.90,Organic,Sprinkler,Yes,950.74
1973,Harvest Agricultural Association,Nigeria,Wheat,64.74,30,No,SMS,745.33,Organic,Sprinkler,No,653.33
1997,Prairie Cultivators Club,Ghana,Rice,89.37,43,No,Mobile Apps,603.02,Organic,Drip,No,958.79

In [118]:
total_achieved_organic = len(achieved_organic)

In [119]:
total_achieved_organic

277

## Q6: Climate-Smart Agriculture Adoption
**Business Question:** In high-rainfall regions (over 1000mm annually), which countries have farming communities that have invested in weather monitoring technology?

**Context:** Weather station adoption in high-rainfall areas indicates sophisticated climate risk management practices.

In [126]:

high_rainfall_regions =  african_agirculture_info[african_agirculture_info['Annual_Rainfall'] > 1000]

TypeError: '>' not supported between instances of 'str' and 'int'

## Q7: Entry-Level Market Assessment
**Business Question:** Among low-performing farming operations (annual yield under 200), which crop types are most prevalent and may need immediate intervention?

**Context:** Low-yield operations represent potential clients for productivity improvement solutions.

In [124]:
low_performing_farming = african_agirculture_info[african_agirculture_info['Annual_Yield'] < 200]

In [125]:
low_performing_farming

,Community_Name,Country,Crop_Type,Farm_Size,Tech_Adoption_Index,Drone_Usage,Mobile_Tech,Annual_Yield,Fertilizer_Type,Irrigation,Weather_Station,Annual_Rainfall
12,Valley Agricultural Association,Ghana,Barley,99.69,60,No,Mobile Apps,182.56,Organic,Drip,Yes,1163.25
30,Harvest Farmers Union,Nigeria,Sorghum,5.88,83,Yes,Mobile Apps,136.35,NaN,Drip,Yes,1024.79
39,Meadow Agricultural Association,Ghana,Rice,16.93,71,No,NaN,181.94,Organic,NaN,Yes,1052.89
44,River Cultivators Club,Ghana,Barley,31.74,46,Yes,Mobile Apps,198.41,Organic,Drip,Yes,498.94
55,Mountain Agri Society,Nigeria,Wheat,59.81,52,No,SMS,154.01,Organic,Drip,Yes,1137.86
...,...,...,...,...,...,...,...,...,...,...,...,...
1950,Valley Agricultural Association,Tanzania,Wheat,43.91,9,No,SMS,150.15,Inorganic,Drip,Yes,519.95
1965,Mountain Farmers Group,Tanzania,Maize,22.47,88,Yes,SMS,139.24,Organic,Sprinkler,No,1100.21
1966,Valley Cultivators Club,Ghana,Rice,86.62,96,No,SMS,184.45,NaN,NaN,No,483.89
1978,Meadow Agri Society,Kenya,Wheat,2.19,2,Yes,NaN,112.96,Inorganic,NaN,Yes,643.36
1992,Valley Farmers Union,Tanzania,Barley,40.12,49,Yes,SMS,178.31,NaN,Drip,Yes,845.96

In [127]:
total_low_peforming_farming = len(low_performing_farming)

In [128]:
total_low_peforming_farming

237

## Q8: Digital Agriculture Penetration
**Business Question:** What irrigation methods are most commonly used by digitally-enabled farming communities (those using Mobile Apps or SMS technology)?

**Context:** Understanding technology adoption patterns helps design integrated digital agriculture solutions.

## Q9: Large-Scale Technology Investment Patterns
**Business Question:** What is the average technology adoption level among large-scale farming operations (90+ acres), and how does it compare to smaller operations?

**Context:** Large farms typically have higher investment capacity and can be early adopters of expensive technologies.


## Q10: Natural Farming Excellence
**Business Question:** What percentage of farming communities achieve high productivity (over 500 annual yield) without using fertilizers, demonstrating natural farming excellence?

**Context:** High-performing farms without fertilizer inputs represent efficient operations that could mentor others in sustainable practices.